[package]
name = "orbiv"
version.workspace = true
edition = "2024"
description.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
anyhow = "1.0.104"
async-trait = "0.1.91"
jiff = { version = "0.2.35", features = ["serde"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.9.0", features = ["postgres"] }
