[package]
name = "orbiv-migrator-source-rusqlite"
version.workspace = true
edition = "2024"
description.workspace = true
license.workspace = true
readme.workspace = true

[features]
bundled = ["rusqlite/bundled"]

[dependencies]
async-trait = "0.1.91"
jiff = "0.2.35"
orbiv = { path = "../orbiv", version = "0.2.0" }
rusqlite = { version = "0.39.0", default-features = false }
indoc = "2.0.7"
