[package]
name = "examples"
version = "0.1.0"
edition = "2024"

[dependencies]
orbit = { path = "../orbit" }
orbit-migrator-source-sqlx = { path = "../orbit-migrator-source-sqlx" }

anyhow = "1.0.104"
async-trait = "0.1.91"
jiff = { version = "0.2.35", features = ["serde"] }
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.9.0", features = ["postgres"] }
