[package]
name = "examples"
version.workspace = true
edition = "2024"
publish = false
description.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
orbiv = { path = "../orbiv", version = "0.1.0"}
orbiv-migrator-source-sqlx = { path = "../orbiv-migrator-source-sqlx", version = "0.1.0"}

anyhow = "1.0.104"
async-trait = "0.1.91"
jiff = { version = "0.2.35", features = ["serde"] }
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.9.0", features = ["postgres"] }
